
try{
console.log(a+b);
}
catch(err){
    console.log(err);
    console.log('there was an error');
}
console.log("Program now works");

